---
title: "EDA Plot1"
author: ''
date: ''
output: html_document
---

```{r}
##load dataset from file saved locally

##change the path to match local download location
setwd("H:/Coursera/EDA")

##open required libraries
library(data.table)
library(datasets)

## Read outcome data  #change the path to match local download
DF <- read.table("H:/Coursera/EDA/household_power_consumption.txt", header=TRUE, sep = ";", 
                 nrows=2075259, na.string="?", comment.char="")

##changing class of columns to character (helps conversion later)
DFa <- DF 
for(col in c("Global_active_power","Global_reactive_power","Voltage","Global_intensity",
             "Sub_metering_1","Sub_metering_2","Sub_metering_3")) 
            {DF[[col]] <- as.character(DF[[col]])}

##changing class of columns to date / time 
DFa$Date <- as.Date(DFa$Date, '%d/%m/%Y')
DFa$Time <- strptime(DFa$Time, "%H:%M:%S")

##create variable of dates to review for subset 
select<- c("2007-02-01","2007-02-02")

##read specific rows from text for plotting
options(warn=-1)
sb <- subset(DFa, DFa$Date == select)

##changing class of columns to numeric
DFS <- sb 
for(col in c("Global_active_power","Global_reactive_power","Voltage","Global_intensity",
            "Sub_metering_1","Sub_metering_2","Sub_metering_3")) 
            {sb[[col]] <- as.numeric(sb[[col]])}

##create additional variables for plotting
DFS$Days <- weekdays(as.Date(sb$Date, '%d/%m/%Y'))  #does not work for X axis
z1 <- DFS$Sub_metering_1
z2 <- DFS$Sub_metering_2
z3 <- DFS$Sub_metering_3

```

Plot1
```{r, echo=FALSE}
with(DFS, hist(Global_active_power, main="Global Active Power", cex.main=0.9,
               mar=c(3,3,1,1), xlab="Global Active Power (kilowatts)", 
               col="red", breaks=10, cex.lab=0.8, xaxt='n',yaxt='n', xpd=TRUE))
axis(2, at=200*0:1200, font=10, cex.axis=0.8)
axis(1, at=2*0:6, font=10, cex.axis=0.8)
dev.copy(png, file="plot1.png", width=480, height=480) 

```

Plot2
```{r, echo=FALSE}
with(DFS, plot(DFS$Time, DFS$Global_active_power, type="l", 
               xlab="", ylab="Global Active Power (kilowatts)", 
               cex.lab=0.8, cex.axis=0.8, yaxt='n', xpd=TRUE ))
axis(2, at=2*0:10, cex.axis=0.8)
dev.copy(png, file="plot2.png", width=480, height=480) 

```

Plot3
```{r, echo=FALSE}
with(DFS, plot(DFS$Time, z1, mar=c(5,5,3,3), type="l", cex.axis=0.8, xlab="", ylab="Energy sub metering", cex.lab=0.8)) 
lines(DFS$Time,z2,type="l", col="red")
lines(DFS$Time,z3,type="l", col="blue")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"),
       col=c("black","red","blue"), pch="-", cex=0.75, pt.cex=1.5)
dev.copy(png, file="plot3.png", width=480, height=480) 

```

Plot4
```{r, echo=FALSE}
par(mfrow=c(2,2), mar=c(4,4,2,1), oma=c(1,1,2,1)) 
with(DFS, {
    plot(DFS$Time, DFS$Global_active_power, type="l", 
                xlab="", ylab="Global Active Power (kilowatts)", 
                cex.lab=0.6, cex.axis=0.6, xpd=TRUE )
    plot(DFS$Time, DFS$Voltage, type="l", xlab="datetime", ylab="Voltage", cex.lab=0.6, cex.axis=0.6, xpd=TRUE )
    plot(DFS$Time, z1, mar=c(5,5,3,3), type="l", xlab="", ylab="Energy sub metering", cex.lab=0.6, cex.axis=0.6)
        lines(DFS$Time,z2,type="l", col="red")
        lines(DFS$Time,z3,type="l", col="blue")
        legend("topright", legend=c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"),
               col=c("black","red","blue"), pch="-", cex=0.75, pt.cex=1.5)  
    plot(DFS$Time, DFS$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power", 
         cex.lab=0.6, cex.axis=0.6, xpd=TRUE )
    })
dev.copy(png, file="plot4.png", width=480, height=480) 
dev.off()  

```